CREATE TABLE IF NOT EXISTS monsters (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL CHECK (name <> ''),
	health integer,
	description varchar,
	mini_crown varchar,
	large_crown varchar,
	king_crown varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS name_monsters ON monsters (name);
