CREATE TABLE IF NOT EXISTS quests (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL CHECK (name <> ''),
    description varchar,
    goal varchar,
    location varchar,
    conditions varchar,
    client varchar,
    failure_conditions varchar,
    reward_money varchar,
    rewards varchar,
    time_limit varchar,
    max_players varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS name_quests ON quests (name);
