CREATE TABLE IF NOT EXISTS monster_physiologies (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	part varchar,
	sever integer,
	blunt integer,
	ranged integer,
	fire integer,
	water integer,
	lightning integer,
	ice integer,
	dragon integer,
	status integer,
	stamina integer,
	monster_id bigint,
	constraint fk_monster_physiologies_monsters foreign key (monster_id) REFERENCES monsters (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS part_monster_id_monster_physiologies ON monster_physiologies (part, monster_id);
