CREATE TABLE IF NOT EXISTS monster_part_breakabilities (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	part varchar,
	value integer,
	sever varchar,
	extract_color varchar,
	monster_id bigint,
	constraint fk_monster_part_breakabilities_monsters foreign key (monster_id) REFERENCES monsters (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS part_monster_id_monster_part_breakabilities ON monster_part_breakabilities (part, monster_id);
