CREATE TABLE IF NOT EXISTS monster_miscs (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar,
	low_high_rank varchar,
	master_rank varchar,
	exhaust_duration varchar[],
	monster_id bigint,
	constraint fk_monster_miscs_monsters foreign key (monster_id) REFERENCES monsters (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS name_monster_id_monster_miscs ON monster_miscs (name, monster_id);
