CREATE TABLE IF NOT EXISTS items (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar,
    description text,
    rarity varchar,
    max_count varchar,
    buy_cost varchar,
    sell_cost varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS name_items ON items (name);
