CREATE TABLE IF NOT EXISTS quest_rewards (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	amount integer,
	percentage integer,
	item_id bigint,
	quest_id bigint,
	constraint fk_quest_rewards_items foreign key (item_id) REFERENCES items (id),
	constraint fk_quest_rewards_quests foreign key (quest_id) REFERENCES quests (id)
);

-- PostgresPipeline requires a unique index for the Model's insert query
CREATE UNIQUE INDEX IF NOT EXISTS id_quest_rewards ON quest_rewards (id);
