CREATE TABLE IF NOT EXISTS quest_supplies (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	amount integer,
	item_id bigint,
	quest_id bigint,
	constraint fk_quest_supplies_items foreign key (item_id) REFERENCES items (id),
	constraint fk_quest_supplies_quests foreign key (quest_id) REFERENCES quests (id)
);

-- PostgresPipeline requires a unique index for the Model's insert query
CREATE UNIQUE INDEX IF NOT EXISTS id_quest_supplies ON quest_rewards (id);
